spring:
  application:
    name: chatbot_service

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://factory-db.c5g4a4ekcfvb.ap-northeast-2.rds.amazonaws.com:3306/factory_db?useSSL=true&trustServerCertificate=true
    username: root
    password: 12345678

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true


aws:
  region: ap-northeast-2
  bedrock:
    agent-id: "SHFTOIN2IV"
    agent-alias-id: "SDDQKOCNTI"


kind: Application